version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 8000"
    environment:
      - DB_HOST=db
      - DB_NAME=udemy_app
      - DB_USER=admin
      - DB_PASS=admin
    depends_on:
      - db


  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=udemy_app
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin